name: rodrigo abad
favicon: null
layout_spectrum: 0.40862
typography_spectrum: 0.81219
title: Rodrigo Abad
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c25654'
    - '#efb571'
    - '#9fe06b'
    - '#676441'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
