name: abad
favicon: null
layout_spectrum: 0.22156570362858474
typography_spectrum: 0.8553597570862621
title: Rodrigo Abad
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9615818127058446
  lightness: 0.49330985406413674
  saturation: 0.48864723020233214
  rhythmicContrast: 0.17432079440914094
purpose: []
